### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LeCoupa** [balderdashy/sails-docs#1049]
This page: https://sailsjs.com/documentation/concepts/models-and-orm/model-settings

This section: dontUseObjectIds.

> This is disabled by default, for performance reasons. You can enable it with this model setting, or on a per-query basis using **.meta({cascade: true})**.

**Comment by raqem** [comment]
@LeCoupa Thank you for your help!

**Comment by raqem** [comment]
@LeCoupa Sails has always been and still is maintained. We are a small group and do costumer work all built on Sails.js as well as maintain Sails. Because of our customer work we have less time for open source, but because of our customer work the web app version of Sails has truly practical, extensive and tested features.

**Comment by LeCoupa** [comment]
Thanks a lot @raqem that's what I wanted to know. I love sails!

I even made a cheatsheet about it a few months ago. https://github.com/LeCoupa/awesome-cheatsheets/blob/master/backend/sails.js
