### ISSUE TITLE
X-Frame-Options with Lusca does not work

### ISSUE THREAD

**Issue by sahanDissanayake** [balderdashy/sails-docs#326]
Hi I tried this https://github.com/balderdashy/sails-docs/blob/master/concepts/Security/Clickjacking.md

But I still can see my website if I add it as a iframe on another website. Please help

**Comment by rachaelshaw** [comment]
@sahanDissanayake I'm closing this for now because it's not necessarily an issue with the docs, but would you mind posting a question in StackOverflow with a little more detail about what you tried? 

If you figure out what the problem was and find that updating the docs would help, though, a PR to this repo would definitely be appreciated. :)
