### ISSUE TITLE
UX: http://sailsjs.org/#/documentation

### ISSUE THREAD

**Issue by epadillas** [balderdashy/sails-docs#341]
I have some suggestions/comments regarding to the doc pages :beers: 

- Whenever I click on a topic from the concept list on the left, some javascript automatically scrolls my browser to the top of the page. It feels "unnatural" because I didn't scroll up by myself, and I could be reading the concept sub-list that is displayed after the initial click, but I'm taken away from there. With that auto-scroller, I have to scroll down again, find where I left reading, and start again.

- It could be more practical to use less pages for each section/concept. For example, in the "Models and ORM" section, there's more than 10 sub-pages ("Associations", "Dominance", "Attributes" ...). I use ctrl+f a lot to find stuff in doc pages. I could be looking for a specific string (for example, "afterCreate"), whose terminology in the Sails framework is unknown to me. With the current division of the doc pages, it will take a little bit more time to find what I'm looking for (visiting every sub-page and ctrl-f'ing). A good example of long-page documentation is Bootstrap (http://getbootstrap.com/components/). There, if I forgot how to create badges, I'd simply ctrl+f it and it would take less than 3 seconds to find what I was looking for.

**Comment by rachaelshaw** [comment]
@epadillas I think the scrolling could definitely be smoother, but it should probably still scroll you to the top -- we're basically assuming that if you clicked on a link, it's because you wanted to read that section. It may make it more difficult to read the side menu, but it makes it easier to read the docs themselves, which is more of a priority. (Plus, if we completely got rid of the scrolling, someone would probably make a new issue about how navigating to a new docs section doesn't bring you to the top of the page.) 
I think just making the scrolling less abrupt will make going to the top of the page after navigating seem more natural.

As for your second idea, there's probably a bit too much content to have (for example) all of Reference on one page, but it would definitely make sense to have each top-level section of Reference on a single page. It can definitely be in the roadmap, but we may not be able to set up something like that for awhile -- we need to focus on fixing the SEO for the docs before doing much else with them (see #323). If you have time to help out with that issue, it would be much appreciated -- the sooner we get that fixed, the sooner we can focus on the UX more.

**Comment by rachaelshaw** [comment]
Moving this to the [sails website repo](https://github.com/balderdashy/www.sailsjs.org), since this is more of a website feature request then a documentation issue.
