### ISSUE TITLE
Currently indexed documentation URLs don't point to actual content

### ISSUE THREAD

**Issue by justusbluemer** [balderdashy/sails-docs#369]
Hi all,

first of all thank you for your work on Sails, I love using the framework and it has helped me a ton – it's awesome.

One thing I found to be quite challenging escpecially while I was getting started and still think is an unnecessary hurdle is how you can't really find anything in the documentation via Google.
Let's take the search for "sails js change port" for example: https://www.google.de/webhp?#q=sails+js+change+port
The top result is
sailsjs.org/#!documentation/deployment
which according to the description in the result snippet offers the correct solution. However when I click the link I end up at http://sailsjs.org/#/documentation/concepts
This behaviour occurs with basically any sails-related search and it costs a lot of time to track the correct subpage in the docs manually.

The correct URL for the result would be http://sailsjs.org/#/documentation/concepts/Deployment
Unfortunately Google doesn't understand the workings of JS-based sites just yet so I suggest returning an HTTP statuscode 301 (permanent redirect) pointing to the current URLs so Google can index the correct URLs and the programmer in need lands directly on the correct part of the documentation.

**Comment by rachaelshaw** [comment]
@justusbluemer thanks for your suggestions on this issue.  I'm closing this one, because there are about 4 different issues about the Google indexing problem, so it makes sense to just track it in the first issue chronologically that mentioned it (#323).

If you have any time to help with a PR, let me know -- any help we can get is greatly appreciated. :)
