### ISSUE TITLE
Documentation links changed at some point and broke Google's indexing

### ISSUE THREAD

**Issue by kevinburke** [balderdashy/sails-docs#372]
If I search on Google for "sails.config.local" the top result is http://sailsjs.org/#!documentation/config.local, which 404's. I only mention this because I know the page exists and I have a lot of difficulty finding it.

**Comment by justusbluemer** [comment]
Exactly, this makes it very hard to find relevant documentation. I already mentioned this problem here: https://github.com/balderdashy/sails-docs/issues/369

**Comment by zac** [comment]
Definitely a big :+1: from this new Sails user. It's been a pretty frustrating barrier to the learning process because this happens to me about 80% of the time when I search for a Sails concept on Google ([example](https://www.google.com/search?q=%22Global+authorization%22+sails+socket.io)). I usually end up using the badly formatted cached page and hope the documentation isn't out of date.

**Comment by theorye** [comment]
This would help a lot for a newcomer.

**Comment by rachaelshaw** [comment]
@kevinburke @justusbluemer @zac @theorye looks like we have several issues about the Google indexing thing now, so I'm closing this and a few others and leaving #323 open to track it. (That was the first one chronologically.) If any of you are willing/able to help with this, let me know.
