### ISSUE TITLE
sockets.js documentation outdated

### ISSUE THREAD

**Issue by megakoresh** [balderdashy/sails-docs#422]
Please update the docs for the file in anatomy so it doesn't confuse newcomers with the deprecated onConnect and onDisconnect functions and such. Would be nice to also provide a new default version of the file to preview, so people know how to actually configure it now.

**Comment by jub3i** [comment]
Hi @megakoresh feel like submitting a PR? :)

**Comment by megakoresh** [comment]
PR? I don't think I understand. Do you mean pull request? I only started out with sails a month ago and don't know enough to contribute I am afraid. I only just figured out how to replace the onConnect functionality in the first place.

**Comment by jub3i** [comment]
You don't have to update the *entire* document, just update the parts you know are outdated - surely you know enough to do that! :) I know you can contribute because you know there are errors and its easy to fix up some text.

Think how awesome Sails.js would be if everyone who used it contributed 10 minutes. **Be** the change you want to see in the world! If you need help making a pull request just leave a comment.

**Comment by megakoresh** [comment]
I am just afraid I would post something stupid and that would mislead people. But I guess I can mark those sections as outdated.

**Comment by jub3i** [comment]
No one has fixed the `./anatomy/myApp/config/sockets.js.md` file? It still needs to be updated based on https://github.com/balderdashy/sails/blob/master/0.11-migration-guide.md

Making a PR is free and won't affect anyone unless it gets merged. We review all PRs so don't be afraid of making a mistake. We need people to get involved, your help would be very appreciated. 

As an upside you will likely be learning a lot by correcting the docs, and if you make a mistake, then when we review your PR we can help you correct them and you'll learn more :)

**Comment by jub3i** [comment]
I'm closing this and will follow your PR's :+1:
