### ISSUE TITLE
build information should be in readme

### ISSUE THREAD

**Issue by brettimus** [balderdashy/sails-docs#523]
it would be awesome if the README

*  specified the preferred way to
* what `md` parser is used, etc
* had a link to the google group

**Comment by rachaelshaw** [comment]
On it.

**Comment by brettimus** [comment]
thank you!

**Comment by brettimus** [comment]
@rachaelshaw Thanks for adding the link to `doc-templater`!

I know, I know, I know I won't let this go. But are you able to build the docs locally? I've had no such luck, and my issue on the `doc-templater` repo is like Critcketville

**Comment by brettimus** [comment]
To be perfectly clear: 

![image](https://cloud.githubusercontent.com/assets/3201327/9591939/f5c1b4be-4ff3-11e5-88a5-0e981fc76dfe.png)

**Comment by rachaelshaw** [comment]
To build the docs locally, basically I cd into my local sails website project, then do `GITHUB_HOOK_SECRET=someArbitraryPassword sails lift`, then I go into Postman and send a Get request to localhost:1337/refresh with the header `X-Hub-Signtaure: someArbitraryPassword`.

It's kind of needlessly complicated at the moment because we started setting it up to rebuild the docs automatically but never finished getting it working.

**Comment by brettimus** [comment]
Oooooohhhhhhhh the website. The website! I'll try this after work today, thanks. 

B

**Comment by brettimus** [comment]
Alright! Got it. Next step is to link to my local docs. (I'll try to figure that one out myself like a big kid.)

Thank you yet again! :sparkles:
