### ISSUE TITLE
Docs aren't updated on sailsjs.org

### ISSUE THREAD

**Issue by jledentu** [balderdashy/sails-docs#536]
Hi,
The README says:

> Currently, these docs are pushed almost instantaneously to www.sailsjs.org. That will likely continue to happen for the forseeable future. In general, this repo should follow the same versioning strategy as Sails (using tags).

But it seems this is not the case currently. How often is the website updated ?
If the docs are not pushed instantaneously anymore, then we should edit the README file. :pencil2:

**Comment by CWyrtzen** [comment]
Hey @jledentu, thanks for letting is know. We've been working through some major updates. Let me check on the status and have someone give an update.

**Comment by rachaelshaw** [comment]
@jledentu we're working on getting it set up to update the website when the docs are changed as we have time, but at the moment we do have to manually tell it to update. (I went ahead and refreshed the docs on the website, so it should show the recent changes at least.)
If you have a moment to update the README that would be awesome -- otherwise I'll change that later.

Thanks for pointing this out -- I had almost forgotten it wasn't automatically updating anymore. (In the mean time I'll plan on updating them daily or so.)

**Comment by brettimus** [comment]
This seems closeable. Imma close it.
