### ISSUE TITLE
deploy latest version of the docs?

### ISSUE THREAD

**Issue by ultrasaurus** [balderdashy/sails-docs#698]
I spent a while digging through the source code to figure out how to do paramterized queries, then went to add them to the doc and saw that was added Feb 26!

https://github.com/balderdashy/sails-docs/blob/master/reference/waterline/models/query.md

Would be nice to deploy master to the website so folks can enjoy the documentation improvements.

See live page here: http://sailsjs.org/documentation/reference/waterline-orm/models/query

**Comment by Rafi993** [comment]
it is always better to rely on sails docs from npm since they are always at the latest. There will be lag in the documentation staged unless some kind of automated staging is used.

**Comment by brettimus** [comment]
@ultrasaurus which isn't to say that you're right: the website could probably use a refresher! (and thanks for opening an issue)

paging @rachaelshaw maybe?

**Comment by rachaelshaw** [comment]
@brettimus thanks for the heads up.
@ultrasaurus I just recompiled the docs to the website, so it should be live on sailsjs.org soon. In the mean time, you can always get the most recent docs at [preview.sailsjs.org](http://preview.sailsjs.org/), which is set up to auto-deploy when sails-docs master is updated. 

Since we always redeploy the main sailsjs.org manually, I'm setting up a weekly calendar event to remind me to recompile the docs, so hopefully they won't get very out-of-date again.
