### ISSUE TITLE
Annoying use of target="_blank"

### ISSUE THREAD

**Issue by soletan** [balderdashy/sails-docs#756]
Why are all documentation-local links using `target="_blank"` for opening link target in another tab. This causes use of sails documentation becoming "tab hell" very quickly.

**Comment by mikermcneil** [comment]
@soletan I feel you, it's super annoying.  Sorry about the inconvenience!  At some point we had some code that normalized them, but then we removed it because of the docs for past versions of sails w/ different subdomains.  Definitely time to bring that back 👍 

----

If anyone wants to take a stab at it, [here's](https://github.com/balderdashy/www.sailsjs.org/blob/46053b49835886ac2f0d9f2e2aa1ab3b0939e199/api/machines/_project_3549_0.0.43/Compilemarkdowndocs.js#L113-L114) the spot to do it.  I'd suggest replacing those two lines with almost the same thing, but using [a custom replacer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace), e.g.

```js
html = html.replace(/(href="https?:\/\/([^"]+)")/g, function (match, p1, p2, p3, offset, string){
  // Check if this is an external link that is ALSO not a link to some page
  // on `*sailsjs.com` or `*.sailsjs.org`.
  var isExternal;// TODO

  // If it is external, then add target="_blank" so it opens in a new tab.
  var newHtmlAttrsSnippet;// TODO

  return newHtmlAttrsSnippet;
});
```

**Comment by rachaelshaw** [comment]
Just updated the sails website to do that check, so should only open new tabs for external links now.

**Comment by soletan** [comment]
That's great news. Website has become a much better place for day to day work now. Thanks!

**Comment by soletan** [comment]
Still not working in all cases:

http://sailsjs.org/documentation/reference/application/sails-lift is linking to http://preview.sailsjs.org/documentation/reference/application/sails-load which is residing in a separate subdomain. Latter page is linking back to http://sailsjs.org/documentation/reference/configuration/sails-config-bootstrap which is not residing in that subdomain any more. Probably due to that it still gets opened in a separate tab.

**Comment by mikermcneil** [comment]
@soletan ah -- in places where there are preview links, those are accidental  (cc @rachaelshaw )
