### ISSUE TITLE
Sails 1.0 migration guide: mention sails.controllers

### ISSUE THREAD

**Issue by cschwaderer** [balderdashy/sails-docs#925]
In Sails 0.12 I made heavy use of `sails.controllers...` Since in Sails 1.0, these won't work any more, I guess they have been removed from. However, there is no mention the migration guide whether controllers where removed from Sails object, why, and how to replace it.

**Comment by sgress454** [comment]
Hi @cschwaderer -- `sails.controllers` was not a documented, public property in v0.12.x, which is why its absence doesn't show up in the migration guide.  

In Sails 1.0, controllers are more of a virtual concept -- they represent organized groups of actions, which can mean a folder of individual action files _or_ a traditional `*Controller.js` file.  If you want get a list of controllers, the best way would probably be to call [`sails.getActions()`](https://github.com/balderdashy/sails-docs/blob/165e1cea5531710cb4437d9a76e449219de5c264/reference/application/advanced-usage/sails.getActions.md), and then split the keys of the resulting dictionary on `/` -- the first part will be the "controller" name (or if there is no `/`, then the action can be considered part of the "index" or "base" controller).
