### ISSUE TITLE
.validate method in model classes usage documentation

### ISSUE THREAD

**Issue by mp3por** [balderdashy/sails-docs#935]
Hello,

In the [migration guide](https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md) you say: 

`The experimental .validate() method in model classes (e.g. User.validate()) is now fully supported, but its usage has changed. See the **.validate() docs** for more info.`

However **.validate() docs** does not lead anywhere. 

Please fix :)

**Comment by rachaelshaw** [comment]
@mp3por looks like there's a link in there there, but it doesn't go anywhere on sailsjs.com proper since we still have the 0.12 docs up. We have to leave it as-is so the links will get compiled correctly when we _do_ put the 1.0 docs on the main site, but in the mean time that page is online [here](https://next.sailsjs.com/documentation/reference/waterline-orm/models/validate) if you need to reference it
