### ISSUE TITLE
npm ERR! notarget No matching version found for sails@^1.0.0

### ISSUE THREAD

**Issue by AskYous** [balderdashy/sails-docs#954]
The [upgrading docs](https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md) say to run `npm install -g --save sails@^1.0.0`. I ran it and npm errored saying: `npm ERR! notarget No matching version found for sails@^1.0.0`.

**Comment by rachaelshaw** [comment]
@AskYous since we're preparing to release the new version soon, some of the instructions in that upgrade guide are being written as if 1.0 were already official -- so yeah, those install instructions won't actually work as-written until it's been released. I updated the version we mention in the upgrade guide so it will work for folks trying to upgrade in the mean time:
```
npm install -g sails@^1.0.0-44
```

**Comment by AskYous** [comment]
Thanks @rachaelshaw
