### ISSUE TITLE
Some of the documentation pages are not found

### ISSUE THREAD

**Issue by abdoolly** [balderdashy/sails-docs#967]
This pages are returning 404 not found error :

- https://sailsjs.com/documentation/concepts/extending-sails/hooks/events
- https://sailsjs.com/documentation/reference/application/advanced-usage/lifecycle
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-get-route-for
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-lift
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-load
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-lower
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-request
- https://sailsjs.com/documentation/reference/application/advanced-usage/sails-get-base-url

this is just in the Application section in the reference page i didn't try other pages
thanks

**Comment by rachaelshaw** [comment]
@abdoolly thanks for pointing this out. Should be fixed now, but only if you click the links on the reference page/side menu; the links listed here won't actually go anywhere because they aren't 0.12 documentation pages -- they're pages in the 1.0 docs. (The redirects for pages that were moved or removed in the 1.0 docs were taking effect when they shouldn't have been. All of those pages should exist on next.sailsjs.com though.)

**Comment by abdoolly** [comment]
Oka thanks for your support @rachaelshaw
